### ISSUE TITLE
Add 3.0 compatible branch/tag?

### ISSUE THREAD

**Issue by stephenmcm** [silverstripe/silverstripe-secureassets#19]
The current composer.json has `"silverstripe/framework": "~3.1"` with some mild testing and looking through the current code, the current master seems 3.0 compatible. Having a tag/branch that is set to  `"silverstripe/framework": "~3.0"` would save people forking the repo to just to change the composer.json or otherwise avoiding composer all together.

**Comment by robbieaverill** [comment]
Closing as we don't support SS 3.4 or lower at time of writing

**Comment by dhensby** [comment]
3.0 and 3.1 are not compatible anyway :P
