### ISSUE TITLE
Warning on folder save

### ISSUE THREAD

**Issue by philbenoit** [silverstripe/silverstripe-secureassets#20]
Warning at framework/forms/Form.php line 1398: Invalid argument supplied for foreach() (http://dev.gateway.com.au/admin/assets/EditForm)

Its the buttonClicked function within the Form.php file thats causing the error. Any ideas?

**Comment by quinnmerio** [comment]
Also having this issue. Were you able to find a fix or workaround?

**Comment by philbenoit** [comment]
I dont believe so. Check your versions of silverstripe, both framework and cms and the version of the secure forms. I dont think it impacted anything in the save process.

**Comment by dhensby** [comment]
Looks like the `buttonClicked` function needs to be a bit more defensive to ensure it doesn't try to iterate a null value.

**Comment by robbieaverill** [comment]
Unfortunately, [SilverStripe 3 has entered limited support in June 2018](https://www.silverstripe.org/blog/update-on-silverstripe-5-x/). This means we'll only be fixing critical bugs and security issues for SilverStripe 3 going forward.

You can read the [SilverStripe Roadmap](https://www.silverstripe.org/software/roadmap/) for more information on our support commitments.
