### ISSUE TITLE
Add translation to messages

### ISSUE THREAD

**Issue by NoLdman** [silverstripe/silverstripe-secureassets#21]
This module seems to be implemented only for English users, it would be nice to have translatable text (i.e. SecureFileController.php line 51:  `Security::permissionFailure($this, _t('SecureFileController.NOTAUTHORIZED', 'You are not authorised to access this resource. Please log in.'));`

**Comment by robbieaverill** [comment]
Unfortunately, [SilverStripe 3 has entered limited support in June 2018](https://www.silverstripe.org/blog/update-on-silverstripe-5-x/). This means we'll only be fixing critical bugs and security issues for SilverStripe 3 going forward.

You can read the [SilverStripe Roadmap](https://www.silverstripe.org/software/roadmap/) for more information on our support commitments.
