### ISSUE TITLE
Deprecate for 4.0

### ISSUE THREAD

**Issue by tractorcow** [silverstripe/silverstripe-secureassets#38]
Secure asset control will become a core feature in 4.0, so this module will likely need to be deprecated at that point.

See https://github.com/silverstripe/silverstripe-framework/pull/4863

**Comment by NightJar** [comment]
Hey team,

I'd like to make a PR to close this issue, however I'm not quite sure what the process is here. Do I just update the readme to say "Don't use this anymore with `silverstripe/framework` 4.0.0+" (or something a bit more verbose to that effect)?

**Comment by robbieaverill** [comment]
Seems good to me!
