### ISSUE TITLE
Not compatible with SilverStripe 3.3

### ISSUE THREAD

**Issue by bummzack** [silverstripe/silverstripe-secureassets#42]
Version 3.3 seems to have introduced a new way of generating resampled images (probably to transition over to SilverStripe 4.0).
Resampled images are now placed in a folder that contains some sort of hash, eg:
`_resampled/FillWyI1MCIsIjUwIl0/MyFileName.jpg`

Therefore, the [pattern](https://github.com/silverstripe-labs/silverstripe-secureassets/blob/master/code/SecureFileController.php#L519) that detects a resampled image no longer works. Accessing a resampled image via `SecureFileController` always returns the full resolution image.

**Comment by jonom** [comment]
I don't have a solution for this but for background the hash was introduced in 3.2 from memory (a years old feature from master), and moving the hash to a directory name instead of regenerated file name came in 3.3.

**Comment by roed** [comment]
And why not use the pattern:
````
/_resampled\//
````
Instead of:
````
/_resampled\/[^-]+-/
````

It works in my case. And you're still checking whether they access a file in the resampled directory.

**Comment by tractorcow** [comment]
Anyone feel like writing a unit test / fix for this? :P

**Comment by roed** [comment]
Made a fix, but not a unit test. I didn't know how to setup the system to write a test, and the current tests didn't cover resampled images.

**Comment by dhensby** [comment]
It seems like we'll need to make sure our composer constraints are fairly strict about how we target SS versions, then. People will need a different release of this module for 3.1, 3.2 and 3.3+

**Comment by roed** [comment]
The code should work on SS 3.1 and 3.2 too, as the images are still in the _resampled folder. The only difference is that SS 3.3 write the images to `hashfolder/originalname.ext` instead of `propertiesofresample-originalname.ext`. The regex covers both cases.

**Comment by dhensby** [comment]
@roed ah, ok, thanks.

**Comment by robbieaverill** [comment]
Looks like this is fixed in #51 - feel free to reopen if that's not the case
