### ISSUE TITLE
Broken Files (Images)

### ISSUE THREAD

**Issue by innomedia** [silverstripe/silverstripe-secureassets#48]
Whenever securing folders all files are corupted. It seems like a linefeed is added at the beginning of every file processed by the SecureFileController - no matter if Content-Description is set to attachment or inline. Seems to work in windows - breaks under linux. Any Ideas?

**Comment by dhensby** [comment]
@innomedia can you give me some specifics of versions of SS/this module you're using as well as the PHP, apache and OS versions?

**Comment by innomedia** [comment]
Thanks for your lightning fast reply. After hours of searching it was a closing php tag in a _config.php which caused the linefeed at the beginning of every output. Sorry for the inconvenience.

**Comment by dhensby** [comment]
I've tried to replicate this on framework/cms `3.4.x-dev` and `1.1.2` of secure assets and I don't experience any asset corruption. Have you confirmed this bug on a fresh install?

I'm serving requests through a CentOS 7.2 VM running locally.

Inspecting the code I see no reason why we'd be getting a `lf` added to the pages.

I *suspect* this may be an issue with your code (perhaps a rogue closing php tag or some other new line hiding away in your files) causing this problem. If you load a regular page on your site and view-source do you see a blank line before the html output starts? If so, it would confirm my suspicions that it's something in your project.

**Comment by dhensby** [comment]
> Thanks for your lightning fast reply. After hours of searching it was a closing php tag in a _config.php which caused the linefeed at the beginning of every output. Sorry for the inconvenience.

Ah, replied just before me. OK, really glad you found it!

**Comment by innomedia** [comment]
Yeah - thank you very much. This drove me nuts for over 6 hours.
