### ISSUE TITLE
Add test for downloading resampled images

### ISSUE THREAD

**Issue by dhensby** [silverstripe/silverstripe-secureassets#52]
Currently there are no tests for downloading resampled images. this has mean regressions between 3.1, 3.2 and 3.3 of framework have been missed

**Comment by robbieaverill** [comment]
Unfortunately, [SilverStripe 3 has entered limited support in June 2018](https://www.silverstripe.org/blog/update-on-silverstripe-5-x/). This means we'll only be fixing critical bugs and security issues for SilverStripe 3 going forward.

You can read the [SilverStripe Roadmap](https://www.silverstripe.org/software/roadmap/) for more information on our support commitments.
