### ISSUE TITLE
SecureFileController never called

### ISSUE THREAD

**Issue by xini** [silverstripe/silverstripe-secureassets#61]
Not sure if this is the right place to post this. 

A bit of history: I am trying to implement 301 redirects for files stored in assets. I got into this issue when we rebuilt a site and discovered that we get a lot of 403 'not allowed' errors for files in the assets directory that have moved.
When a folder exists, but a file in that folder doesn't, you get a 404 error (e.g. `www.domain.tld/assets/folder/nofile.pdf`), as expected.
But when you hit an URL to a file in a non-existing folder, you get a 403 (e.g. `www.domain.tld/non-existing/no-file.pdf`).

The 403 errors are caused by ‘Deny from all’ in the assets/.htaccess file. This seems to have priority over any redirects added to the main .htaccess file for files that have changed path. It looks like the ‘Deny from all’ prohibits apache from checking whether the file actually exists.

To fix that, I have removed the global ‘Deny from all’ and changed the regex to the following using a negation:
```
<FilesMatch "\.(!(?i:html|htm|xhtml|js|css|bmp|png|gif|jpg|jpeg|ico|pcx|...|jar|xml|pdf|gpx|kml))$">
	Deny from all
</FilesMatch>
```
Is that safe to use? Should that be merged into core?

Now for the actual secureassets issue: The SecureFileController of the secureassets module is never called because of the 
```
RewriteCond %{REQUEST_FILENAME} !-f
```
in the root .htaccess file. This means that any 404 handler in SS (e.g. misdirection, etc) don’t work for asset files. 

If I add 
```
RewriteCond %{REQUEST_URI} ^assets/ [NC,OR]
```
right before that line in the main .htaccess file, this works, but it also means that every request to a file goes through the whole SS controller stuff, which makes the site slower (but I guess this is what is to be expected with the secureassets module?). With this the 404 handlers also works for asset files.

As is, the secureassets module relies entirely on the .htaccess files set in the secured folders, without any controller logic involved. 
Is it intentional that the SecureFileController isn't used? 
Should the implementation be changed or at least the docs enhanced?

Thanks.

**Comment by tractorcow** [comment]
Related: https://github.com/silverstripe/silverstripe-framework/issues/7690

**Comment by robbieaverill** [comment]
Unfortunately, [SilverStripe 3 has entered limited support in June 2018](https://www.silverstripe.org/blog/update-on-silverstripe-5-x/). This means we'll only be fixing critical bugs and security issues for SilverStripe 3 going forward.

You can read the [SilverStripe Roadmap](https://www.silverstripe.org/software/roadmap/) for more information on our support commitments.

**Comment by xini** [comment]
Just wait long enough and all the problems will go away... Great solution.

**Comment by robbieaverill** [comment]
Hey @xini, the recommended fix for this problem would be to upgrade to use the latest version of SilverStripe 4, where this module's functionality comes out of the box.

The community is always welcome to submit patches for problems like this, but limited support means that the core team no longer has scope to look at it =)
