### ISSUE TITLE
Document upgrade path for SS3 with secure assets to SS4 with core functionality

### ISSUE THREAD

**Issue by robbieaverill** [silverstripe/silverstripe-secureassets#63]
Devs using secureassets on SS3, particularly CWP 1.x, will migrate their projects to SS4 which includes the functionality from this module in core.

From memory when I reviewed the code between the two they were similar enough that no explicit upgrade path was required, but we should sanity check this and document the process - i.e. if it's the case that nothing extra is required, then "when you've upgraded your project, ensure you run the file migration task [that you'd need to run for SS3 to SS4 assets in general anyway]".

**Comment by raissanorth** [comment]
Testing this surfaced https://github.com/silverstripe/silverstripe-asset-admin/issues/777
