### ISSUE TITLE
ShowInSearch should default to 0

### ISSUE THREAD

**Issue by emteknetnz** [silverstripe/silverstripe-secureassets#69]
File.ShowInSearch should be set to 0 for files that go into a secure assets folder

There should be a yml config option to change this to 1 if desired, because this may be desired if the person performing the search has relevant canView() permissions

Probably the most standard use case for secureassets is a public user uploads files from a UserDefinedForms.  By default, UserDefinedForms will set ShowInSearch = 0

However, if there is a custom form, or another method of adding files to a secureassets folder, then ShowInSearch retains its default value of 1 which is set in File.php  - this leads to the not so good scenario where secure assets may show in search if a custom search engine does not have a canView() check

SS4 version of this issue: https://github.com/silverstripe/silverstripe-assets/issues/247

**Comment by NightJar** [comment]
Can you please explain the use case where these files are showing in search results but you expect them not to?
Because it seems to me more that the permission level of the person searching should be accounted for when presenting the results, not that no protected files should show ever (by default). This would be in line with the way that pages work when showing results, for example.

**Comment by emteknetnz** [comment]
Main issue here is that things don't always work as intended due to human error somewhere along the line.  

In a perfect world you can always assume there will be a canView() before displaying search results, and if you simply use a default cwp install then you'll be fine.  However out in the wild people do all sorts of customisations ... and "securefiles" may show up in search results =/

**Comment by NightJar** [comment]
Ok, seems like a safe default rather than a "proper" thing to do. I'm happy with that, so long as the commit message includes such a description :)

**Comment by NightJar** [comment]
The only issue I see is that this will effectively remove all search results of existing sites that upgrade, which is technically a breaking change I suppose...

**Comment by maxime-rainville** [comment]
Unfortunately, [SilverStripe 3 has entered limited support in June 2018](https://www.silverstripe.org/blog/update-on-silverstripe-5-x/). This means we'll only be fixing critical bugs and security issues for SilverStripe 3 going forward.

You can read the [SilverStripe Roadmap](https://www.silverstripe.org/software/roadmap/) for more information on our support commitments.
