### ISSUE TITLE
Filename sensitivity 

### ISSUE THREAD

**Issue by asecondwill** [silverstripe/silverstripe-secureassets#8]
Through a form on our site, users have uploaded resume.pdf and Resume.pdf

Each user has the correct file attached to their application in model admin, but when clicking through to view the PDF, the lower case version is always displayed.

The folder the resumes are stored in is secured for view by logged in users only.

**Comment by robbieaverill** [comment]
I'm going to close this under the assumption that the PR at #9 has been closed, the framework issue  silverstripe/silverstripe-framework#3017 has been labelled as a major change (so, will go into SS4) and this module will not be relevant in SS4.
